### ISSUE TITLE
missing a descriptive Readme

### ISSUE THREAD

**Issue by alexxa** [djzager/kubevirt-olm#5]
Please add a descriptive Readme. Thanks!

**Comment by djzager** [comment]
@alexxa if you could check out the README.md and let me know if there is any more useful information that I could add, that would be helpful.

**Comment by alexxa** [comment]
please add that it's for OS 4.0 only.

**Comment by djzager** [comment]
I made that change in this PR https://github.com/kubevirt/olm-manifests/pull/1

My understanding is that the goal is to move the important stuff into that repository and throw this one away. Please do checkout the README included in that PR and comment if you see any issues, it helps a ton.
